/**
 * Self-contained replacement for the Franz cloud API.
 *
 * Runs a tiny HTTP server on localhost inside the main process and answers
 * every endpoint the renderer calls (auth, user, services, recipes,
 * workspaces, features, news, payment). Data lives in JSON files under the
 * app's userData directory. Recipes are served from the bundled
 * `recipes-bundle` directory (generated by scripts/sync-recipes.sh).
 */
import http from 'http';
import path from 'path';
import fs from 'fs-extra';
import jwt from 'jsonwebtoken';
import { v4 as uuid } from 'uuid';
import semver from 'semver';
import { app } from 'electron';

const debug = require('debug')('Franz:LocalServer');

const HOST = '127.0.0.1';
const PREFERRED_PORT = 45569;
const TOKEN_SECRET = 'franz-local-server';
const USER_ID = '1';

const DEFAULT_USER = {
  id: USER_ID,
  email: 'franz@localhost',
  firstname: 'Franz',
  lastname: 'Local',
  organization: '',
  accountType: 'individual',
  emailValidated: true,
  beta: false,
  locale: 'en-US',
  isPremium: true,
  isSubscriptionOwner: true,
  hasSubscription: true,
  hadSubscription: false,
  team: null,
};

const DEFAULT_SERVICE = {
  isEnabled: true,
  isNotificationEnabled: true,
  isBadgeEnabled: true,
  isIndirectMessageBadgeEnabled: true,
  isMuted: false,
  isDarkModeEnabled: false,
  isHibernationEnabled: false,
  spellcheckerLanguage: null,
  customUrl: '',
  team: '',
  order: 99,
  hasCustomIcon: false,
  iconUrl: null,
};

const FEATURES = {
  isSpellcheckerIncludedInCurrentPlan: true,
  needToWaitToProceed: false,
  appDelaysEnabled: false,
  isServiceProxyEnabled: true,
  isServiceProxyIncludedInCurrentPlan: true,
  isAnnouncementsEnabled: false,
  isWorkspaceEnabled: true,
  isWorkspaceIncludedInCurrentPlan: true,
  isServiceLimitEnabled: false,
  serviceLimitCount: 0,
  isCommunityRecipesIncludedInCurrentPlan: true,
  isCustomUrlIncludedInCurrentPlan: true,
  isTodosEnabled: true,
  isTodosIncludedInCurrentPlan: true,
  isPlanSelectionEnabled: false,
  isTrialStatusBarEnabled: false,
  isMagicBarEnabled: false,
};

class JsonStore {
  constructor(file, fallback) {
    this.file = file;
    this.fallback = fallback;
  }

  read() {
    try {
      return fs.readJsonSync(this.file);
    } catch (e) {
      return JSON.parse(JSON.stringify(this.fallback));
    }
  }

  write(data) {
    fs.outputJsonSync(this.file, data, { spaces: 2 });
    return data;
  }
}

function parseMultipart(buffer, contentType) {
  const match = /boundary=(?:"([^"]+)"|([^;]+))/i.exec(contentType);
  if (!match) return {};
  const boundary = `--${match[1] || match[2]}`;
  const result = {};
  let start = buffer.indexOf(boundary);

  while (start !== -1) {
    start += boundary.length;
    if (buffer.slice(start, start + 2).toString() === '--') break;
    const headerEnd = buffer.indexOf('\r\n\r\n', start);
    if (headerEnd === -1) break;
    const next = buffer.indexOf(boundary, headerEnd);
    const headers = buffer.slice(start, headerEnd).toString();
    const body = buffer.slice(headerEnd + 4, next === -1 ? buffer.length : next - 2);
    const name = /name="([^"]+)"/.exec(headers);
    const filename = /filename="([^"]*)"/.exec(headers);
    const type = /Content-Type:\s*([^\r\n]+)/i.exec(headers);
    if (name) {
      result[name[1]] = filename
        ? { filename: filename[1], contentType: type ? type[1] : 'application/octet-stream', data: body }
        : body.toString();
    }
    start = next;
  }

  return result;
}

export default class LocalServer {
  constructor() {
    const dataDir = path.join(app.getPath('userData'), 'local-server');
    this.iconsDir = path.join(dataDir, 'icons');
    this.users = new JsonStore(path.join(dataDir, 'user.json'), DEFAULT_USER);
    this.services = new JsonStore(path.join(dataDir, 'services.json'), []);
    this.workspaces = new JsonStore(path.join(dataDir, 'workspaces.json'), []);

    this.bundleDir = path.join(__dirname, '..', 'recipes-bundle');
    this.recipes = this.readBundleJson('all.json', []);
    this.featured = this.readBundleJson('featured.json', []);

    fs.ensureDirSync(this.iconsDir);
  }

  readBundleJson(file, fallback) {
    try {
      return fs.readJsonSync(path.join(this.bundleDir, file));
    } catch (e) {
      console.error(`LocalServer: could not read ${file}`, e);
      return fallback;
    }
  }

  get baseUrl() {
    return `http://${HOST}:${this.port}`;
  }

  start() {
    return new Promise((resolve) => {
      const server = http.createServer((req, res) => this.handle(req, res));
      server.on('error', (err) => {
        if (err.code === 'EADDRINUSE') {
          debug('Port in use, picking a random one');
          server.listen(0, HOST);
        } else {
          throw err;
        }
      });
      server.on('listening', () => {
        this.port = server.address().port;
        debug('Listening on', this.baseUrl);
        resolve(this.baseUrl);
      });
      server.listen(PREFERRED_PORT, HOST);
      this.server = server;
    });
  }

  // ---------------------------------------------------------------- helpers

  token() {
    return jwt.sign({
      iss: 'Franz Local Server',
      sub: DEFAULT_USER.email,
      userId: USER_ID,
    }, TOKEN_SECRET, { expiresIn: '100y' });
  }

  recipePreview(recipe) {
    return {
      ...recipe,
      icons: {
        svg: `${this.baseUrl}/v1/recipes/icon/${recipe.id}.svg`,
      },
    };
  }

  serviceIconUrl(service) {
    if (!service.iconId) return null;
    return `${this.baseUrl}/v1/icon/${service.iconId}`;
  }

  serialiseService(service) {
    return {
      ...DEFAULT_SERVICE,
      ...service,
      userId: USER_ID,
      iconUrl: this.serviceIconUrl(service),
      hasCustomIcon: Boolean(service.iconId),
    };
  }

  async readBody(req) {
    return new Promise((resolve) => {
      const chunks = [];
      req.on('data', c => chunks.push(c));
      req.on('end', () => resolve(Buffer.concat(chunks)));
    });
  }

  json(res, status, data) {
    res.writeHead(status, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(data));
  }

  file(res, filePath, contentType) {
    if (!fs.existsSync(filePath)) {
      this.json(res, 404, { message: 'Not found' });
      return;
    }
    res.writeHead(200, { 'Content-Type': contentType, 'Cache-Control': 'no-cache' });
    fs.createReadStream(filePath).pipe(res);
  }

  // ---------------------------------------------------------------- routing

  async handle(req, res) {
    try {
      const url = new URL(req.url, this.baseUrl);
      const segments = url.pathname.split('/').filter(Boolean);
      const raw = ['POST', 'PUT'].includes(req.method) ? await this.readBody(req) : null;
      const contentType = req.headers['content-type'] || '';
      let body = {};
      if (raw && raw.length) {
        body = contentType.includes('multipart/form-data')
          ? parseMultipart(raw, contentType)
          : JSON.parse(raw.toString() || '{}');
      }

      debug(req.method, url.pathname);

      if (segments[0] === 'health') {
        return this.json(res, 200, { api: 'success', db: 'success' });
      }

      if (segments[0] !== 'v1') {
        return this.json(res, 404, { message: 'Not found' });
      }

      const [, resource, ...rest] = segments;
      const handler = this.routes()[`${req.method} ${resource}`];
      if (!handler) return this.json(res, 404, { message: 'Not found', path: url.pathname });

      return handler(res, rest, body, url);
    } catch (err) {
      console.error('LocalServer error', err);
      return this.json(res, 500, { message: err.message });
    }
  }

  routes() {
    return {
      // ---- auth
      'POST auth': (res, [action]) => {
        if (action === 'login' || action === 'signup') {
          return this.json(res, 200, { message: 'ok', token: this.token() });
        }
        return this.json(res, 200, { message: 'ok' });
      },
      'POST invite': res => this.json(res, 200, { message: 'ok' }),

      // ---- user
      'GET me': (res, [sub]) => {
        if (sub === 'services') {
          return this.json(res, 200, this.services.read().map(s => this.serialiseService(s)));
        }
        return this.json(res, 200, { ...DEFAULT_USER, ...this.users.read() });
      },
      'PUT me': (res, _, body) => {
        const user = this.users.write({
          ...DEFAULT_USER, ...this.users.read(), ...body, id: USER_ID,
        });
        return this.json(res, 200, { data: user, status: ['data-updated'] });
      },
      'DELETE me': (res) => {
        this.services.write([]);
        this.workspaces.write([]);
        this.users.write(DEFAULT_USER);
        return this.json(res, 200, { message: 'ok' });
      },

      // ---- services
      'POST service': (res, _, body) => {
        const services = this.services.read();
        const service = {
          ...DEFAULT_SERVICE,
          ...body,
          id: uuid(),
          order: services.length,
        };
        delete service.iconFile;
        services.push(service);
        this.services.write(services);
        return this.json(res, 200, { data: this.serialiseService(service), status: ['created'] });
      },
      'PUT service': (res, [id], body) => {
        const services = this.services.read();

        if (id === 'reorder') {
          services.forEach((s) => {
            if (body[s.id] !== undefined) s.order = body[s.id];
          });
          this.services.write(services);
          return this.json(res, 200, services.map(s => this.serialiseService(s)));
        }

        const service = services.find(s => s.id === id);
        if (!service) return this.json(res, 404, { message: 'Service not found' });

        if (body.icon && body.icon.data) {
          const ext = (body.icon.filename.split('.').pop() || 'png').toLowerCase();
          const iconId = `${id}-${Date.now()}.${ext}`;
          if (service.iconId) fs.removeSync(path.join(this.iconsDir, service.iconId));
          fs.writeFileSync(path.join(this.iconsDir, iconId), body.icon.data);
          service.iconId = iconId;
        } else {
          if (body.customIcon === 'delete' && service.iconId) {
            fs.removeSync(path.join(this.iconsDir, service.iconId));
            service.iconId = null;
          }
          Object.assign(service, body);
          delete service.iconFile;
          delete service.customIcon;
        }

        this.services.write(services);
        return this.json(res, 200, { data: this.serialiseService(service), status: ['updated'] });
      },
      'DELETE service': (res, [id]) => {
        const services = this.services.read();
        const service = services.find(s => s.id === id);
        if (service && service.iconId) fs.removeSync(path.join(this.iconsDir, service.iconId));
        this.services.write(services.filter(s => s.id !== id));
        return this.json(res, 200, { message: 'Successfully deleted service', status: 200 });
      },
      'GET icon': (res, [iconId]) => {
        const safe = path.basename(iconId);
        const ext = safe.split('.').pop();
        const types = {
          png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif', svg: 'image/svg+xml', webp: 'image/webp',
        };
        return this.file(res, path.join(this.iconsDir, safe), types[ext] || 'application/octet-stream');
      },

      // ---- recipes
      'GET recipes': (res, [action, arg], _, url) => {
        if (!action) {
          return this.json(res, 200, this.recipes.map(r => this.recipePreview(r)));
        }
        if (action === 'popular') {
          const featured = this.recipes.filter(r => this.featured.includes(r.id) || r.featured);
          return this.json(res, 200, featured.map(r => this.recipePreview(r)));
        }
        if (action === 'search') {
          const needle = (url.searchParams.get('needle') || '').toLowerCase();
          const results = this.recipes.filter(r => (
            r.id.toLowerCase().includes(needle) || (r.name || '').toLowerCase().includes(needle)
          ));
          return this.json(res, 200, results.map(r => this.recipePreview(r)));
        }
        if (action === 'download') {
          const id = path.basename(arg || '');
          return this.file(res, path.join(this.bundleDir, 'archives', `${id}.tar.gz`), 'application/gzip');
        }
        if (action === 'icon') {
          const id = path.basename(arg || '').replace(/\.svg$/, '');
          return this.file(res, path.join(this.bundleDir, 'icons', `${id}.svg`), 'image/svg+xml');
        }
        const recipe = this.recipes.find(r => r.id === action);
        if (!recipe) return this.json(res, 404, { message: 'Recipe not found' });
        return this.json(res, 200, this.recipePreview(recipe));
      },
      'POST recipes': (res, [action], body) => {
        if (action !== 'update') return this.json(res, 404, { message: 'Not found' });
        const updates = Object.keys(body).filter((id) => {
          const bundled = this.recipes.find(r => r.id === id);
          if (!bundled) return false;
          try {
            return semver.gt(bundled.version, body[id]);
          } catch (e) {
            return false;
          }
        });
        return this.json(res, 200, updates);
      },

      // ---- workspaces
      'GET workspace': res => this.json(res, 200, this.workspaces.read()),
      'POST workspace': (res, _, body) => {
        const workspaces = this.workspaces.read();
        const workspace = {
          id: uuid(),
          name: body.name,
          order: workspaces.length,
          services: [],
          userId: USER_ID,
        };
        workspaces.push(workspace);
        this.workspaces.write(workspaces);
        return this.json(res, 200, workspace);
      },
      'PUT workspace': (res, [id], body) => {
        const workspaces = this.workspaces.read();
        const workspace = workspaces.find(w => w.id === id);
        if (!workspace) return this.json(res, 404, { message: 'Workspace not found' });
        if (body.name !== undefined) workspace.name = body.name;
        if (body.services !== undefined) workspace.services = body.services;
        this.workspaces.write(workspaces);
        return this.json(res, 200, workspace);
      },
      'DELETE workspace': (res, [id]) => {
        this.workspaces.write(this.workspaces.read().filter(w => w.id !== id));
        return this.json(res, 200, { message: 'Successfully deleted workspace' });
      },

      // ---- features, payment, news, misc
      'GET features': res => this.json(res, 200, FEATURES),
      'GET payment': res => this.json(res, 200, { month: { id: 'local', price: 0 }, year: { id: 'local', price: 0 } }),
      'POST payment': res => this.json(res, 200, { message: 'ok' }),
      'GET news': (res, [id]) => this.json(res, 200, id ? { message: 'ok' } : []),
      'GET announcements': res => this.json(res, 404, { message: 'No announcements' }),
      'GET poweredby': res => this.json(res, 200, {}),
    };
  }
}
