// Services
export const RELOAD_SERVICE = 'RELOAD_SERVICE';
export const NAVIGATE_SERVICE_TO = 'NAVIGATE_SERVICE_TO';
export const OPEN_SERVICE_DEV_TOOLS = 'OPEN_SERVICE_DEV_TOOLS';
export const INITIALIZE_SERVICE_WEBVIEW = 'INITIALIZE_SERVICE_CONTEXT_MENU';
export const UPDATE_SPELLCHECKING_LANGUAGE = 'UPDATE_SPELLCHECKING_LANGUAGE';
export const REQUEST_SERVICE_SPELLCHECKING_LANGUAGE = 'REQUEST_SERVICE_SPELLCHECKING_LANGUAGE';
export const SERVICE_SPELLCHECKING_LANGUAGE = 'SERVICE_SPELLCHECKING_LANGUAGE';
export const RESIZE_SERVICE_VIEWS = 'RESIZE_SERVICE_VIEWS';
export const RESIZE_TODO_VIEW = 'RESIZE_TODO_VIEW';
export const HIDE_ALL_SERVICES = 'HIDE_ALL_SERVICES';
export const SHOW_ALL_SERVICES = 'SHOW_ALL_SERVICES';
export const GET_ACTIVE_SERVICE_WEB_CONTENTS_ID = 'GET_ACTIVE_SERVICE_WEB_CONTENTS_ID';
export const ACTIVATE_SERVICE = 'ACTIVATE_SERVICE';
export const ACTIVATE_PREVIOUS_SERVICE = 'ACTIVATE_PREVIOUS_SERVICE';
export const ACTIVATE_NEXT_SERVICE = 'ACTIVATE_NEXT_SERVICE';
export const UPDATE_SERVICE_STATE = 'UPDATE_SERVICE_STATE';

// Overlay replacement for modals
export const OVERLAY_OPEN = 'OVERLAY_OPEN';
export const OVERLAY_SHARE_SETTINGS = 'OVERLAY_SHARE_SETTINGS';

// Settings
export const GET_SETTINGS = 'REQUEST_SETTINGS';
export const SEND_SETTINGS = 'SEND_SETTINGS';

// Share Franz Dialog
export const SHARE_FRANZ_GET_SERVICE_COUNT = 'SHARE_FRANZ_GET_SERVICE_COUNT';

// Plan Selection Dialog
export const PLAN_SELECTION_GET_DATA = 'PLAN_SELECTION_GET_DATA';
export const PLAN_SELECTION_TRIGGER_ACTION = 'PLAN_SELECTION_TRIGGER_ACTION';

// Todos
export const TODOS_FETCH_WEB_CONTENTS_ID = 'TODOS_FETCH_WEB_CONTENTS_ID';
export const TODOS_TOGGLE_DRAWER = 'TODOS_TOGGLE_DRAWER';
export const TODOS_TOGGLE_ENABLE_TODOS = 'TODOS_TOGGLE_ENABLE_TODOS';
export const TODOS_RELOAD = 'TODOS_RELOAD';
export const TODOS_OPEN_DEV_TOOLS = 'TODOS_OPEN_DEV_TOOLS';

// User
export const USER_LOGIN_STATUS = 'USER_LOGIN_STATUS';

// Settings
export const SETTINGS_NAVIGATE_TO = 'SETTINGS_NAVIGATE_TO';

// Workspaces
export const WORKSPACE_TOGGLE_DRAWER = 'WORKSPACE_TOGGLE_DRAWER';
export const WORKSPACE_OPEN_SETTINGS = 'WORKSPACE_OPEN_SETTINGS';
export const WORKSPACE_ACTIVATE = 'WORKSPACE_ACTIVATE';

// General
export const FETCH_DEBUG_INFO = 'FETCH_DEBUG_INFO';
export const TOGGLE_FULL_SCREEN = 'TOGGLE_FULL_SCREEN';
export const CHECK_MACOS_PERMISSIONS = 'CHECK_MACOS_PERMISSIONS';
export const RELOAD_APP = 'RELOAD_APP';

// App control
export const APP_SHOW_MAIN_WINDOW = 'APP_SHOW_MAIN_WINDOW';
export const APP_QUIT = 'APP_QUIT';
export const APP_MINIMIZE_WINDOW = 'APP_MINIMIZE_WINDOW';
export const APP_CLOSE_WINDOW = 'APP_CLOSE_WINDOW';
export const APP_DOCK_BOUNCE = 'APP_DOCK_BOUNCE';
export const APP_GET_DISPLAYS = 'APP_GET_DISPLAYS';
export const APP_SET_LOGIN_ITEM_SETTINGS = 'APP_SET_LOGIN_ITEM_SETTINGS';
export const APP_GET_LOGIN_ITEM_SETTINGS = 'APP_GET_LOGIN_ITEM_SETTINGS';
export const POWER_MONITOR_EVENT = 'POWER_MONITOR_EVENT';
export const NATIVE_THEME_UPDATED = 'NATIVE_THEME_UPDATED';

// Touch bar
export const TOUCH_BAR_SET = 'TOUCH_BAR_SET';
export const TOUCH_BAR_CLICK = 'TOUCH_BAR_CLICK';

// Menus and dialogs
export const MENU_POPUP = 'MENU_POPUP';
export const APPLICATION_MENU_SET = 'APPLICATION_MENU_SET';
export const APPLICATION_MENU_POPUP = 'APPLICATION_MENU_POPUP';
export const APPLICATION_MENU_CLICK = 'APPLICATION_MENU_CLICK';
export const DIALOG_MESSAGE_BOX = 'DIALOG_MESSAGE_BOX';

// webContents
export const WEB_CONTENTS_INVOKE = 'WEB_CONTENTS_INVOKE';
export const WEB_CONTENTS_SEND = 'WEB_CONTENTS_SEND';
export const WEB_CONTENTS_WATCH_NAVIGATION = 'WEB_CONTENTS_WATCH_NAVIGATION';
export const WEB_CONTENTS_NAVIGATION_EVENT = 'WEB_CONTENTS_NAVIGATION_EVENT';
export const WEB_CONTENTS_CLOSE_WINDOW = 'WEB_CONTENTS_CLOSE_WINDOW';

// Sessions
export const SESSION_CLEAR_CACHE = 'SESSION_CLEAR_CACHE';
export const SESSION_CLEAR_STORAGE_DATA = 'SESSION_CLEAR_STORAGE_DATA';
export const SESSION_SET_PROXY = 'SESSION_SET_PROXY';

// App
export const APP_VALUES = 'APP_VALUES';

// Relay
export const RELAY_MESSAGE = 'RELAY_MESSAGE';
